Tercera entrega
Khamul04/baz-android-course pull request #3
Opened 2022-10-04 07:42 UTC by Khamul04

En el pull request anterior
1) Se creó un view pager para mostrar las tres pantallas.
2) La pestaña de COIN consume el end point: https://api.bitso.com/v3/available_books y guarda el resultado en local usando room
3) La pestaña Asks consume el endpoint: https://api.bitso.com/v3/order_book, el book a traer lo consulta de la base de datos local guardado en la pestaña coin. Muestra en la vista los asks que se recibieron del servicio
4) La pestaña Bids es similar a asks, pero muestra las bids que se recibieron en el servicio
5) Se agregaron imágenes de algunas monedas
6) cada pantalla cuenta con su viewModel
7) Se usaron corutinas para manejar las peticiones en segundo plano.
8) Se usa ConstraintLayout para la vista.
9) Se usa un recyclerview para mostrar los datos de cada servicio
10) Se usan funciones de extension y lambdas
11) Se usaron las propiedades: tail recursive, propiedades delegadas y operaciones con colecciones
En el pull request actual
1) Se agregó la pantalla de detalle
2) Se creo el ViewModel y se consumen los servicios de la pantalla de detalle
3)Se agrego navigation controler pra navegar entre la pantalla principal y el detalle de las monedas
4) Se agregaron mas monedas
5) Se paso linter por el proyecto

2022-10-07 19:17 UTC, cecydb11-wizeline commented on app/src/main/java/com/example/wizelineproject/screens/MainFragment.kt
> +        //binding.viewPager.adapter = viewPagerAdapter
Trata de limpiar un poco el código de lo que no vayas a usar en vez de dejarlo comentado.

2022-10-07 19:18 UTC, cecydb11-wizeline commented on app/src/main/java/com/example/wizelineproject/screens/CoinsFragment.kt
> +/*
Mencionas que usaste el linter pero no se ve que haya formateado todos estos espacios aquí y en otras partes del código, podrías revisar eso?

2022-10-07 19:22 UTC, cecydb11-wizeline commented on app/src/main/java/com/example/wizelineproject/screens/viewholders/CoinViewHolder.kt
> +        else if(book.book.startsWith("ltc"))
Aquí podrías buscar otra forma de implementarlo pues "hardcodeado" no es tan escalable en caso de que se añadieran nuevas monedas, podrías nombrar el archivo de la imagen por ejemplo "btc_image" e igual haciendo la validación de las letras con las que empieza podrías tomar la imagen correspondiente.

2022-10-07 19:23 UTC, cecydb11-wizeline commented on app/src/main/java/com/example/wizelineproject/screens/viewholders/TransactionViewHolder.kt
> +        val stringToText = "$"+transaction.price
Podrías hacer uso de una función extendida, parecida a la que se usaba en el ejercicio de prueba cuando tuviste la entrevista, para formatear en automático el precio a que ya sea string con el signo de pesos.

2022-10-07 19:24 UTC, cecydb11-wizeline requested changes
Añadi algunos comentarios.

2022-10-08 06:45 UTC, Khamul04 commented on app/src/main/java/com/example/wizelineproject/screens/CoinsFragment.kt
> +/*
Aquí lo que hice fue correr lint (./gradlew lint) y efectué las correcciones que me marcó (algunas, porque otras no aplicaban).
Volví a ejecutar lint y para la entrega final y se hicieron los cambios solicitados.

2022-10-08 06:49 UTC, Khamul04 commented
Enviaré un ultimo pull request, con los cambios que me solicitas: 
   1) Limpiar código
   2) Quitar las imágenes hardcodeadas
   3) Ejecuté lint para dar mejor formato al código

2022-10-08 06:49 UTC, merged